eddie_wrapper improvements: eddie output on exit is only emailed to $EDDIE_ADMIN if the Eddie return-code is non-zero.  By default no $EDDIE_ADMIN is set (so no email is sent by default) and $EDDIE_ADMIN can now be defined outside the eddie_wrapper script (ie: in a startup script).

diff --git a/eddie/trunk/bin/eddie_wrapper b/eddie/trunk/bin/eddie_wrapper
--- a/eddie/trunk/bin/eddie_wrapper
+++ b/eddie/trunk/bin/eddie_wrapper
@@ -24,10 +24,16 @@
 ## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 ########################################################################
 
-## Address to receive restart messages.  Set to empty or comment out to
-##   disable sending messages.
-#EDDIE_ADMIN=eddie-adm@domain.name
-EDDIE_ADMIN=root
+## Address to receive restart messages, including tracebacks for any
+##   bad exceptions.  Set to empty or comment out to disable sending
+##   messages.  If set as an environment variable it will not be
+##   over-written.  Defaults to not set.
+
+if [ $EDDIE_ADMIN = "" ]
+then
+    #EDDIE_ADMIN=eddie-adm@domain.name
+    EDDIE_ADMIN=
+fi
 
 ## Failure to start EDDIE-Tool after MAX_RETRIES in a short period of time
 ##   indicates a serious problem.  eddie_wrapper will then die.
@@ -46,20 +52,20 @@ RUNFILE=/var/run/eddie/tmp/eddie$$.out
 
 ## Create (if necessary) /var/run/eddie/tmp
 if [ ! -d /var/run/eddie/tmp ]; then
- 	mkdir -p /var/run/eddie/tmp >/dev/null 2>&1
-	if [ $? -gt 0 ]; then
-		echo '$0: "mkdir -p /var/run/eddie/tmp" failed.'
-		RUNFILE=/var/tmp/eddie$$.out
-        fi
+    mkdir -p /var/run/eddie/tmp >/dev/null 2>&1
+    if [ $? -gt 0 ]; then
+	echo '$0: "mkdir -p /var/run/eddie/tmp" failed.'
+	RUNFILE=/var/tmp/eddie$$.out
+    fi
 fi
 
 ## Find mail program
 if [ -x /bin/mailx ]; then		# Solaris
-	MAIL=/bin/mailx
+    MAIL=/bin/mailx
 elif [ -x /bin/mail ]; then		# Linux
-	MAIL=/bin/mail
+    MAIL=/bin/mail
 else
-	MAIL=mail				# dunno...
+    MAIL=mail				# dunno...
 fi
 
 ## clean up a bit
@@ -69,14 +75,14 @@ rm -f /var/run/eddie/tmp/*.out
 PGREP=`which pgrep`
 if [ "$PGREP" = "" ]
 then
-	PGREP="useps"
+    PGREP="useps"
 fi
 
 ## Find eddie/bin/
 EDDIEPATH=`dirname $0`
 if [ "$EDDIEPATH" = "" ]
 then
-	EDDIEPATH="."
+    EDDIEPATH="."
 fi
 
 
@@ -85,53 +91,63 @@ fi
 tries=0
 
 while [ 1 ]; do
-    	if [ "$PGREP" = "useps" ]
-	then
-	    pid=`ps -ef | grep \.\*python\.\*eddie.py  | grep -v grep | awk '{ print $2 }'`
-	else
-	    pid=`$PGREP eddie.py`
-	fi
+    if [ "$PGREP" = "useps" ]
+    then
+	pid=`ps -ef | grep \.\*python\.\*eddie.py  | grep -v grep | awk '{ print $2 }'`
+    else
+	pid=`$PGREP eddie.py`
+    fi
 
-        if [ "${pid}" != "" ]; then
-                echo "Error: Eddie is already running."
-                exit 2
-        fi
+    if [ "${pid}" != "" ]; then
+	echo "Error: Eddie is already running."
+	exit 2
+    fi
 
-	#start_time=`$GDATE "+%s"`
-	start_time=`$PYTHON -c "import time ; print int(time.time())"`
+    #start_time=`$GDATE "+%s"`
+    start_time=`$PYTHON -c "import time ; print int(time.time())"`
 
-	$EDDIEPATH/eddie.py >>$RUNFILE
+    $EDDIEPATH/eddie.py >>$RUNFILE
 
-	retcode=$?
+    retcode=$?
+
+    if [ $retcode -ne 0 ]
+    then
 	echo "eddie_wrapper: eddie died at `date` return code: $retcode" >> $RUNFILE
 
 	curtime=`$PYTHON -c "import time ; print int(time.time())"`
 	restart_time=`expr $curtime - $start_time`
 	if [ $restart_time -lt 120 ]; then
-		tries=`expr $tries + 1`
+	    tries=`expr $tries + 1`
 	else
-		tries=0
+	    tries=0
 	fi
 
 	if [ $tries -gt $MAX_TRIES ]; then
-		echo "eddie_wrapper: Too many restarts ($tries) in a short time. eddie_wrapper quitting." >>$RUNFILE
-
-		if [ "$EDDIE_ADMIN" != "" ]
-		then
-			$MAIL -s "Eddie output on `hostname` at `date`" $EDDIE_ADMIN < $RUNFILE
-		fi
-		rm $RUNFILE
-		exit 3
+	    echo "eddie_wrapper: Too many restarts ($tries) in a short time. eddie_wrapper quitting." >>$RUNFILE
 	fi
 
 	if [ "$EDDIE_ADMIN" != "" ]
 	then
-		$MAIL -s "Eddie output on `hostname` at `date`" $EDDIE_ADMIN < $RUNFILE
+	    # Sent output to EDDIE_ADMIN if defined
+	    $MAIL -s "Eddie output on `hostname` at `date`" $EDDIE_ADMIN < $RUNFILE
+	else
+	    # Otherwise to stdout
+	    cat $RUNFILE
 	fi
 	rm -f $RUNFILE
 
-	sleep 30
-	echo "eddie_wrapper: restarting Eddie at `date` [tries=$tries]." >> $RUNFILE
+	if [ $tries -gt $MAX_TRIES ]; then
+	    exit 3
+	fi
+
+	sleep 60
+    else
+	sleep 5
+    fi
+
+    rm -f $RUNFILE
+
+    echo "eddie_wrapper: restarting Eddie at `date` [tries=$tries]." >> $RUNFILE
 done
 
 # clean up some more
