Added some more smarts to eddie_wrapper: - don't start Eddie if one is already running. - don't restart Eddie more than a set number of times in a short period of time.

diff --git a/eddie/trunk/bin/eddie_wrapper b/eddie/trunk/bin/eddie_wrapper
--- a/eddie/trunk/bin/eddie_wrapper
+++ b/eddie/trunk/bin/eddie_wrapper
@@ -22,9 +22,11 @@
 # Address to receive restart messages
 EDDIE_ADMIN=eddie-adm
 
+MAX_TRIES=10	# only restart MAX_TRIES time in a short period of time
 
-# Set path for mail/sleep/etc
-PATH=/bin:/usr/bin
+
+# Set path for mail/sleep/gtime/etc
+PATH=/bin:/usr/bin:/opt/local/bin
 export PATH
 
 
@@ -63,13 +65,37 @@ fi
 # clean up a bit
 rm -f /var/run/eddie/tmp/*.out
 
+tries=0
 
 while [ 1 ]; do
+	pid=`/usr/bin/ps -ef | /usr/bin/grep \.\*python\.\*eddie.py  | grep -v grep | awk '{ print $2 }'`
+        if [ "${pid}" != "" ]; then
+                echo "Error: Eddie is already running."
+                exit 2
+        fi
+
+	start_time=`gdate "+%s"`
+
 	cd /opt/eddie/bin
 	./eddie.py >$RUNFILE
+
 	retcode=$?
 	echo "eddie_wrapper: eddie died at `date` return code: $retcode" >> $RUNFILE
 	$MAIL -s "Eddie output on `hostname` at `date`" $EDDIE_ADMIN < $RUNFILE
+
+	curtime=`gdate "+%s"`
+	restart_time=`expr $curtime - $start_time`
+	if [ $restart_time -lt 120 ]; then
+		tries=`expr $tries + 1`
+	else
+		tries=0
+	fi
+
+	if [ $tries > $MAX_TRIES ]; then
+		echo "Too many restarts ($tries) in a short time. eddie_wrapper quitting." | $MAIL -s "eddie_wrapper on `hostname`: Too many restarts ($tries) in a short time." $EDDIE_ADMIN
+		exit 3
+	fi
+
 	sleep 30
 	echo "eddie_wrapper: restarting Eddie at `date`."
 done
